### ISSUE TITLE
Create comments for DatasetLoader

### ISSUE THREAD

**Issue by brianRey2017** [midusi/handshape_datasets#4]
- [x] _Get_downloaded_flag
- [x] _Get_status_flag
- [x] _Get_preprocessed_flag
- [x] _Load
- [x] _Get_klass_id_for_filename
- [x] _Preprocess
- [x] _Set_downloaded
- [x] _Set_preprocessed_flag
- [x] _Set_status_flag

**Comment by brianRey2017** [comment]
@facundoq
Esta función tiene un parametro value que no termino de entender cual es su uso
```
def _set_status_flag(self, path, status, value=True):
        """
        Flags are used as a way to control that a stage ended successfully.
        This method creates a file used for that control process.

        Args:
            path(str): The path where the status file will be created
            status(str): The name of the status file
        """
        status_path = os.path.join(path, status)
        if not os.path.exists(status_path):
            open(status_path, 'a').close()
        else:
            raise ValueError(f"Status {status} already set on {path}")
```

**Comment by brianRey2017** [comment]
All the work is done. @facundoq Check the comments. If you approve it, close the issue :smile:

**Comment by facundoq** [comment]
@brianRey2017 El value estaba originalmente para que si es True se cree el archivo, y si es False se borre. Después me di cuenta que no era necesario porque no tiene sentido poner en False eso.

Quedó joya!
