### ISSUE TITLE
get_cannonicTable doesn't exist

### ISSUE THREAD

**Issue by AmitMY** [midusi/handshape_datasets#44]
I'm looking for a way to match every class to its actual "name" / representative image.

The README hints at a function `get_cannonicTable`, but such function doesn't exist.

> To obtain the Cannonic Table with ASL you may execute the function get_cannonicTable() like this:
> ```
>   handshape_datasets.get_cannonicTable()
> ```

**Comment by facundoq** [comment]
Thanks, fixed in the _develop_ branch!
