### ISSUE TITLE
Clasify each dataset and subsets for Hand's Class Id

### ISSUE THREAD

**Issue by brianRey2017** [midusi/handshape_datasets#8]
Clasify each dataset and subsets for hand's class Id

- [ ] aslA
- [ ] aslB
- [ ] ciarp
- [ ] indian_trainig
- [ ] irish
- [ ] jsl 
- [ ] nus_1
- [ ] psl
- [ ] pugeault
- [ ] rwth

**Comment by facundoq** [comment]
Note: we generally call the class simply "class", not "class id"

**Comment by facundoq** [comment]
You can check https://github.com/midusi/handshape_datasets/blob/develop/handshape_datasets/datasets_helpers/lsa16.py to check how to return the class and subject information
